version: "3.8"

# Оптимизированная конфигурация для RunPod с высокопроизводительными GPU

services:
  mangio-rvc-runpod-optimized:
    build:
      context: .
      dockerfile: Dockerfile.runpod.optimized
      args:
        - BUILDKIT_INLINE_CACHE=1
    image: mangio-rvc-runpod-optimized:latest
    container_name: mangio-rvc-runpod-optimized
    runtime: nvidia
    environment:
      # GPU оптимизации
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
      - TORCH_CUDA_ARCH_LIST=7.0;7.5;8.0;8.6;8.9;9.0
      - CUDA_LAUNCH_BLOCKING=0
      - CUDNN_BENCHMARK=1
      - PYTORCH_CUDA_ALLOC_CONF=max_split_size_mb:512

      # Оптимизации параллелизма
      - OMP_NUM_THREADS=8
      - MKL_NUM_THREADS=8
      - NUMEXPR_NUM_THREADS=8

      # TensorRT оптимизации
      - TENSORRT_PRECISION=FP16

      # Настройки приложения
      - TZ=UTC
      - RVC_NO_AUTOOPEN=1

    ports:
      - "3000:3000"
    volumes:
      # RunPod workspace монтирование
      - /workspace/logs:/app/logs
      - /workspace/weights:/app/weights
      - /workspace/audio-outputs:/app/audio-outputs
      - /workspace/datasets:/app/datasets
      - /workspace/audios:/app/audios
      - /workspace/pretrained:/app/pretrained
      - /workspace/pretrained_v2:/app/pretrained_v2
      - /workspace/uvr5_weights:/app/uvr5_weights
      - /workspace/hubert_base.pt:/app/hubert_base.pt:ro
      - /workspace/rmvpe.pt:/app/rmvpe.pt:ro

    restart: unless-stopped
    stdin_open: true
    tty: true

    # Ресурсы с учетом высокопроизводительных GPU
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
        limits:
          memory: 32G

    # Настройки сети для быстрого доступа
    network_mode: host

    # Запуск с оптимизацией
    command: ["python", "-u", "infer-web.py", "--port", "3000", "--noautoopen"]

    # Health checks для автоматического перезапуска
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
