version: "3.8"

services:
  mangio-rvc-cpu:
    build:
      context: .
      dockerfile: Dockerfile.cpu
    container_name: mangio-rvc-cpu
    environment:
      - TZ=Europe/Moscow
    ports:
      - "7865:7865"
    volumes:
      # Монтируем директории для сохранения данных
      - ./logs:/app/logs
      - ./weights:/app/weights
      - ./audio-outputs:/app/audio-outputs
      - ./datasets:/app/datasets
      - ./audios:/app/audios
      # Монтируем предобученные модели
      - ./pretrained:/app/pretrained
      - ./pretrained_v2:/app/pretrained_v2
      - ./uvr5_weights:/app/uvr5_weights
      - ./hubert_base.pt:/app/hubert_base.pt:ro
      - ./rmvpe.pt:/app/rmvpe.pt:ro
      # Монтируем формант пресеты
      - ./formantshiftcfg:/app/formantshiftcfg
    restart: unless-stopped
    stdin_open: true
    tty: true
    # Ограничения ресурсов для CPU
    deploy:
      resources:
        limits:
          cpus: "8"
          memory: 16G
